services:
    db:
        image: postgres:latest
        platform: 'linux/amd64'
        restart: always
        environment:
            - POSTGRES_DB=${DATABASE_DB}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - ./.data/database:/var/lib/postgresql/data
        ports:
            - "${DATABASE_PORT_OUT}:5432"

    app:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - db
